cam_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: CAMUserBundle:Default:index }

cam_user_index:
    path:     /user/index
    defaults: { _controller: CAMUserBundle:User:index }

cam_user_articles:
    path:     /user/articles/{page}
    defaults: { _controller: CAMUserBundle:User:articles, page: 1 }
    requirements: 
      page: \d+

emm_user_add:
    path:     /user/add
    defaults: { _controller: EMMUserBundle:User:add }

emm_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: EMMUserBundle:User:edit }

emm_user_view:
    path:     /user/view/{id}
    defaults: { _controller: EMMUserBundle:User:view }

emm_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: EMMUserBundle:User:delete }  

