<?php

namespace IEPC\OficialiaPartesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * pruebaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pruebaRepository extends EntityRepository
{
}
